name: 更新脚本
description: 提交新版本脚本文件
title: "Update: 脚本更新"
labels: ["Update"]
body:
  - type: textarea
    id: update_log
    attributes:
      label: 更新日志
      placeholder: e.g. 修复了 xxx 问题
    validations:
      required: true

  - type: textarea
    id: file_upload
    attributes:
      label: 脚本文件
      placeholder: 将文件拖拽至此...
    validations:
      required: true
